version: '2'
services:
  web:
    build: ./web
    hostname: web
    container_name: web
    ports:
      - '8080:80'
    volumes_from:
      - storage
  storage:
    build: ./storage
    hostname: storage
    container_name: storage
    #volumes:
    #  - ../src:/opt
